sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php: 7.0

env:
  global:
    - CODE_COVERAGE=false

# We have decided to only test the latest two of each major releases.
  matrix:
    - MAGENTO_VERSION=2.1.12
    - MAGENTO_VERSION=2.1.13
    - MAGENTO_VERSION=2.2.3
    - MAGENTO_VERSION=2.2.4
    - MAGENTO_VERSION=2.2.5

matrix:
# PHP 7.1 would be supported in Magento since Magento 2.2
# And there wouldn't be support of PHP 7.1 in Magento 2.0 or 2.1
  include:
    - php: 7.1
      env: MAGENTO_VERSION=2.2.4 CODE_COVERAGE=true

before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash scripts/dependencies.sh
  - bash scripts/setup.sh

script:
  - grunt phpcs
  - grunt lint
  - grunt exec:ciTests
  - if [ "$CODE_COVERAGE" = "false" ]; then php /tmp/magento2/bin/magento setup:di:compile; fi # Check for compilation errors

after_success:
  - bash scripts/AfterSuccess.sh

cache:
  directories:
  - node_modules
  - $HOME/.download_cache
  - $HOME/.composer
  - $HOME/.cache/composer